//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.XPO.ORMDataModel
{

    public partial class Items : XPObject
    {
        Product _Product;
        public Product Product
        {
            get { return _Product; }
            set { SetPropertyValue<Product>(nameof(Product), ref _Product, value); }
        }
        string _ProductName;
        public string ProductName
        {
            get { return _ProductName; }
            set { SetPropertyValue<string>(nameof(ProductName), ref _ProductName, value); }
        }
        decimal _Price;
        public decimal Price
        {
            get { return _Price; }
            set { SetPropertyValue<decimal>(nameof(Price), ref _Price, value); }
        }
        int _Quantity;
        public int Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref _Quantity, value); }
        }
        Order _Order;
        [Association(@"ItemsReferencesOrder")]
        public Order Order
        {
            get { return _Order; }
            set { SetPropertyValue<Order>(nameof(Order), ref _Order, value); }
        }
        [PersistentAlias("[Quantity] * [Price]")]
        public decimal TotalItemPrice
        {
            get { return (decimal)(EvaluateAlias(nameof(TotalItemPrice))); }
        }
    }

}
