//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.XPO.ORMDataModel
{
    public partial class Product : XPObject
    {
        string _ProductName;
        public string ProductName
        {
            get { return _ProductName; }
            set { SetPropertyValue<string>(nameof(ProductName), ref _ProductName, value); }
        }
        decimal _Price;
        public decimal Price
        {
            get { return _Price; }
            set { SetPropertyValue<decimal>(nameof(Price), ref _Price, value); }
        }
        Category _Category;
        [Association(@"ProductReferencesCategory")]
        public Category Category
        {
            get { return _Category; }
            set { SetPropertyValue<Category>(nameof(Category), ref _Category, value); }
        }
    }

}
